namespace WinformDemo
{
    partial class NavigationBarExtForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem1 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(NavigationBarExtForm));
            System.Drawing.Drawing2D.GraphicsPath graphicsPath1 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem2 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath2 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem3 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath3 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem4 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath4 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem5 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath5 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem6 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath6 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem7 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath7 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem8 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath8 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem9 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath9 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem10 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath10 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem11 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath11 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem12 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath12 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem13 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath13 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem14 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath14 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem15 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath15 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem16 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath16 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem17 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath17 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem18 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath18 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem19 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath19 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem20 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath20 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem21 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath21 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem22 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath22 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem23 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath23 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem24 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath24 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem25 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath25 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem26 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath26 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem27 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath27 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem28 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath28 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem29 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath29 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem30 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath30 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem31 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath31 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem32 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath32 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem33 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath33 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem34 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath34 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem35 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath35 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem36 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath36 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem37 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath37 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem38 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath38 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem39 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath39 = new System.Drawing.Drawing2D.GraphicsPath();
            WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem navigationBarItem40 = new WinformControlLibraryExtension.NavigationBarExt.NavigationBarItem();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath40 = new System.Drawing.Drawing2D.GraphicsPath();
            this.navigationBarExt8 = new WinformControlLibraryExtension.NavigationBarExt();
            this.navigationBarExt7 = new WinformControlLibraryExtension.NavigationBarExt();
            this.navigationBarExt6 = new WinformControlLibraryExtension.NavigationBarExt();
            this.navigationBarExt5 = new WinformControlLibraryExtension.NavigationBarExt();
            this.navigationBarExt4 = new WinformControlLibraryExtension.NavigationBarExt();
            this.navigationBarExt3 = new WinformControlLibraryExtension.NavigationBarExt();
            this.navigationBarExt2 = new WinformControlLibraryExtension.NavigationBarExt();
            this.navigationBarExt1 = new WinformControlLibraryExtension.NavigationBarExt();
            this.propertyGrid1 = new System.Windows.Forms.PropertyGrid();
            this.SuspendLayout();
            // 
            // navigationBarExt8
            // 
            this.navigationBarExt8.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.navigationBarExt8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(183)))), ((int)(((byte)(107)))));
            this.navigationBarExt8.CausesValidation = false;
            this.navigationBarExt8.ItemDisableTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.navigationBarExt8.ItemEnterTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.navigationBarExt8.ItemInterval = 0;
            this.navigationBarExt8.ItemNormalBackColor = System.Drawing.Color.Empty;
            this.navigationBarExt8.ItemNormalTextColor = System.Drawing.Color.Gray;
            navigationBarItem1.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem1.BackRectF")));
            navigationBarItem1.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem1.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem1.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem1.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem1.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem1.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath1.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem1.Path = graphicsPath1;
            navigationBarItem1.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem1.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem1.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem1.SymbolRectF")));
            navigationBarItem1.Text = "一级菜单";
            navigationBarItem1.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem2.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem2.BackRectF")));
            navigationBarItem2.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem2.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem2.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem2.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem2.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem2.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath2.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem2.Path = graphicsPath2;
            navigationBarItem2.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem2.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem2.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem2.SymbolRectF")));
            navigationBarItem2.Text = "二级菜单";
            navigationBarItem2.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem3.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem3.BackRectF")));
            navigationBarItem3.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem3.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem3.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem3.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem3.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem3.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath3.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem3.Path = graphicsPath3;
            navigationBarItem3.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem3.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem3.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem3.SymbolRectF")));
            navigationBarItem3.Text = "三级菜单";
            navigationBarItem3.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem4.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem4.BackRectF")));
            navigationBarItem4.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem4.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem4.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem4.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem4.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem4.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath4.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem4.Path = graphicsPath4;
            navigationBarItem4.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem4.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem4.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem4.SymbolRectF")));
            navigationBarItem4.Text = "四级菜单";
            navigationBarItem4.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem5.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem5.BackRectF")));
            navigationBarItem5.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem5.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem5.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem5.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem5.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem5.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath5.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem5.Path = graphicsPath5;
            navigationBarItem5.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem5.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem5.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem5.SymbolRectF")));
            navigationBarItem5.Text = "五级菜单";
            navigationBarItem5.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            this.navigationBarExt8.Items.Add(navigationBarItem1);
            this.navigationBarExt8.Items.Add(navigationBarItem2);
            this.navigationBarExt8.Items.Add(navigationBarItem3);
            this.navigationBarExt8.Items.Add(navigationBarItem4);
            this.navigationBarExt8.Items.Add(navigationBarItem5);
            this.navigationBarExt8.ItemStyle = WinformControlLibraryExtension.NavigationBarExt.ItemStyles.ObliqueLine;
            this.navigationBarExt8.Location = new System.Drawing.Point(367, 56);
            this.navigationBarExt8.Name = "navigationBarExt8";
            this.navigationBarExt8.Size = new System.Drawing.Size(570, 24);
            this.navigationBarExt8.SymbolColor = System.Drawing.Color.Gray;
            this.navigationBarExt8.TabIndex = 2;
            this.navigationBarExt8.Text = "navigationBarExt2";
            // 
            // navigationBarExt7
            // 
            this.navigationBarExt7.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.navigationBarExt7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(183)))), ((int)(((byte)(107)))));
            this.navigationBarExt7.CausesValidation = false;
            this.navigationBarExt7.ItemDisableTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.navigationBarExt7.ItemInterval = 4;
            navigationBarItem6.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem6.BackRectF")));
            navigationBarItem6.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem6.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem6.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem6.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem6.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem6.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath6.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem6.Path = graphicsPath6;
            navigationBarItem6.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem6.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem6.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem6.SymbolRectF")));
            navigationBarItem6.Text = "一级菜单";
            navigationBarItem6.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem7.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem7.BackRectF")));
            navigationBarItem7.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem7.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem7.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem7.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem7.NormalBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(204)))), ((int)(((byte)(153)))));
            navigationBarItem7.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath7.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem7.Path = graphicsPath7;
            navigationBarItem7.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem7.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem7.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem7.SymbolRectF")));
            navigationBarItem7.Text = "二级菜单";
            navigationBarItem7.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem8.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem8.BackRectF")));
            navigationBarItem8.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem8.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem8.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem8.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem8.NormalBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            navigationBarItem8.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath8.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem8.Path = graphicsPath8;
            navigationBarItem8.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem8.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem8.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem8.SymbolRectF")));
            navigationBarItem8.Text = "三级菜单";
            navigationBarItem8.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem9.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem9.BackRectF")));
            navigationBarItem9.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem9.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem9.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem9.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem9.NormalBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(102)))), ((int)(((byte)(153)))));
            navigationBarItem9.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath9.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem9.Path = graphicsPath9;
            navigationBarItem9.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem9.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem9.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem9.SymbolRectF")));
            navigationBarItem9.Text = "四级菜单";
            navigationBarItem9.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem10.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem10.BackRectF")));
            navigationBarItem10.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem10.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem10.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem10.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem10.NormalBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            navigationBarItem10.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath10.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem10.Path = graphicsPath10;
            navigationBarItem10.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem10.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem10.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem10.SymbolRectF")));
            navigationBarItem10.Text = "五级菜单";
            navigationBarItem10.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            this.navigationBarExt7.Items.Add(navigationBarItem6);
            this.navigationBarExt7.Items.Add(navigationBarItem7);
            this.navigationBarExt7.Items.Add(navigationBarItem8);
            this.navigationBarExt7.Items.Add(navigationBarItem9);
            this.navigationBarExt7.Items.Add(navigationBarItem10);
            this.navigationBarExt7.ItemStyle = WinformControlLibraryExtension.NavigationBarExt.ItemStyles.Quadrangle;
            this.navigationBarExt7.Location = new System.Drawing.Point(367, 242);
            this.navigationBarExt7.Name = "navigationBarExt7";
            this.navigationBarExt7.Size = new System.Drawing.Size(570, 24);
            this.navigationBarExt7.SymbolColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.navigationBarExt7.TabIndex = 8;
            this.navigationBarExt7.Text = "navigationBarExt7";
            // 
            // navigationBarExt6
            // 
            this.navigationBarExt6.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.navigationBarExt6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(183)))), ((int)(((byte)(107)))));
            this.navigationBarExt6.CausesValidation = false;
            this.navigationBarExt6.ItemDisableTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.navigationBarExt6.ItemInterval = 4;
            this.navigationBarExt6.ItemNormalBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            navigationBarItem11.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem11.BackRectF")));
            navigationBarItem11.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem11.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem11.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem11.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem11.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem11.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath11.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem11.Path = graphicsPath11;
            navigationBarItem11.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem11.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem11.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem11.SymbolRectF")));
            navigationBarItem11.Text = "一级菜单";
            navigationBarItem11.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem12.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem12.BackRectF")));
            navigationBarItem12.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem12.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem12.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem12.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem12.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem12.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath12.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem12.Path = graphicsPath12;
            navigationBarItem12.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem12.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem12.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem12.SymbolRectF")));
            navigationBarItem12.Text = "二级菜单";
            navigationBarItem12.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem13.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem13.BackRectF")));
            navigationBarItem13.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem13.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem13.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem13.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem13.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem13.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath13.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem13.Path = graphicsPath13;
            navigationBarItem13.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem13.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem13.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem13.SymbolRectF")));
            navigationBarItem13.Text = "三级菜单";
            navigationBarItem13.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem14.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem14.BackRectF")));
            navigationBarItem14.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem14.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem14.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem14.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem14.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem14.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath14.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem14.Path = graphicsPath14;
            navigationBarItem14.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem14.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem14.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem14.SymbolRectF")));
            navigationBarItem14.Text = "四级菜单";
            navigationBarItem14.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem15.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem15.BackRectF")));
            navigationBarItem15.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem15.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem15.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem15.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem15.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem15.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath15.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem15.Path = graphicsPath15;
            navigationBarItem15.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem15.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem15.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem15.SymbolRectF")));
            navigationBarItem15.Text = "五级菜单";
            navigationBarItem15.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            this.navigationBarExt6.Items.Add(navigationBarItem11);
            this.navigationBarExt6.Items.Add(navigationBarItem12);
            this.navigationBarExt6.Items.Add(navigationBarItem13);
            this.navigationBarExt6.Items.Add(navigationBarItem14);
            this.navigationBarExt6.Items.Add(navigationBarItem15);
            this.navigationBarExt6.ItemStyle = WinformControlLibraryExtension.NavigationBarExt.ItemStyles.Circular;
            this.navigationBarExt6.Location = new System.Drawing.Point(367, 211);
            this.navigationBarExt6.Name = "navigationBarExt6";
            this.navigationBarExt6.Size = new System.Drawing.Size(570, 24);
            this.navigationBarExt6.SymbolColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.navigationBarExt6.TabIndex = 7;
            this.navigationBarExt6.Text = "navigationBarExt6";
            // 
            // navigationBarExt5
            // 
            this.navigationBarExt5.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.navigationBarExt5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(183)))), ((int)(((byte)(107)))));
            this.navigationBarExt5.CausesValidation = false;
            this.navigationBarExt5.ItemDisableTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.navigationBarExt5.ItemInterval = 4;
            this.navigationBarExt5.ItemNormalBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(102)))), ((int)(((byte)(153)))));
            navigationBarItem16.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem16.BackRectF")));
            navigationBarItem16.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem16.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem16.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem16.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem16.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem16.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath16.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem16.Path = graphicsPath16;
            navigationBarItem16.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem16.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem16.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem16.SymbolRectF")));
            navigationBarItem16.Text = "一级菜单";
            navigationBarItem16.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem17.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem17.BackRectF")));
            navigationBarItem17.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem17.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem17.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem17.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem17.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem17.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath17.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem17.Path = graphicsPath17;
            navigationBarItem17.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem17.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem17.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem17.SymbolRectF")));
            navigationBarItem17.Text = "二级菜单";
            navigationBarItem17.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem18.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem18.BackRectF")));
            navigationBarItem18.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem18.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem18.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem18.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem18.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem18.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath18.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem18.Path = graphicsPath18;
            navigationBarItem18.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem18.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem18.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem18.SymbolRectF")));
            navigationBarItem18.Text = "三级菜单";
            navigationBarItem18.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem19.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem19.BackRectF")));
            navigationBarItem19.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem19.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem19.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem19.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem19.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem19.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath19.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem19.Path = graphicsPath19;
            navigationBarItem19.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem19.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem19.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem19.SymbolRectF")));
            navigationBarItem19.Text = "四级菜单";
            navigationBarItem19.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem20.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem20.BackRectF")));
            navigationBarItem20.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem20.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem20.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem20.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem20.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem20.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath20.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem20.Path = graphicsPath20;
            navigationBarItem20.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem20.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem20.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem20.SymbolRectF")));
            navigationBarItem20.Text = "五级菜单";
            navigationBarItem20.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            this.navigationBarExt5.Items.Add(navigationBarItem16);
            this.navigationBarExt5.Items.Add(navigationBarItem17);
            this.navigationBarExt5.Items.Add(navigationBarItem18);
            this.navigationBarExt5.Items.Add(navigationBarItem19);
            this.navigationBarExt5.Items.Add(navigationBarItem20);
            this.navigationBarExt5.ItemStyle = WinformControlLibraryExtension.NavigationBarExt.ItemStyles.Leaf;
            this.navigationBarExt5.Location = new System.Drawing.Point(367, 180);
            this.navigationBarExt5.Name = "navigationBarExt5";
            this.navigationBarExt5.Size = new System.Drawing.Size(570, 24);
            this.navigationBarExt5.SymbolColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.navigationBarExt5.TabIndex = 6;
            this.navigationBarExt5.Text = "navigationBarExt5";
            // 
            // navigationBarExt4
            // 
            this.navigationBarExt4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.navigationBarExt4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(183)))), ((int)(((byte)(107)))));
            this.navigationBarExt4.CausesValidation = false;
            this.navigationBarExt4.ItemDisableTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.navigationBarExt4.ItemInterval = 4;
            this.navigationBarExt4.ItemNormalBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            navigationBarItem21.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem21.BackRectF")));
            navigationBarItem21.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem21.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem21.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem21.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem21.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem21.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath21.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem21.Path = graphicsPath21;
            navigationBarItem21.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem21.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem21.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem21.SymbolRectF")));
            navigationBarItem21.Text = "一级菜单";
            navigationBarItem21.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem22.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem22.BackRectF")));
            navigationBarItem22.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem22.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem22.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem22.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem22.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem22.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath22.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem22.Path = graphicsPath22;
            navigationBarItem22.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem22.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem22.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem22.SymbolRectF")));
            navigationBarItem22.Text = "二级菜单";
            navigationBarItem22.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem23.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem23.BackRectF")));
            navigationBarItem23.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem23.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem23.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem23.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem23.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem23.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath23.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem23.Path = graphicsPath23;
            navigationBarItem23.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem23.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem23.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem23.SymbolRectF")));
            navigationBarItem23.Text = "三级菜单";
            navigationBarItem23.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem24.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem24.BackRectF")));
            navigationBarItem24.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem24.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem24.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem24.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem24.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem24.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath24.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem24.Path = graphicsPath24;
            navigationBarItem24.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem24.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem24.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem24.SymbolRectF")));
            navigationBarItem24.Text = "四级菜单";
            navigationBarItem24.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem25.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem25.BackRectF")));
            navigationBarItem25.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem25.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem25.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem25.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem25.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem25.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath25.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem25.Path = graphicsPath25;
            navigationBarItem25.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem25.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem25.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem25.SymbolRectF")));
            navigationBarItem25.Text = "五级菜单";
            navigationBarItem25.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            this.navigationBarExt4.Items.Add(navigationBarItem21);
            this.navigationBarExt4.Items.Add(navigationBarItem22);
            this.navigationBarExt4.Items.Add(navigationBarItem23);
            this.navigationBarExt4.Items.Add(navigationBarItem24);
            this.navigationBarExt4.Items.Add(navigationBarItem25);
            this.navigationBarExt4.ItemStyle = WinformControlLibraryExtension.NavigationBarExt.ItemStyles.RoundCap;
            this.navigationBarExt4.Location = new System.Drawing.Point(367, 149);
            this.navigationBarExt4.Name = "navigationBarExt4";
            this.navigationBarExt4.Size = new System.Drawing.Size(570, 24);
            this.navigationBarExt4.SymbolColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.navigationBarExt4.TabIndex = 5;
            this.navigationBarExt4.Text = "navigationBarExt4";
            // 
            // navigationBarExt3
            // 
            this.navigationBarExt3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.navigationBarExt3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(183)))), ((int)(((byte)(107)))));
            this.navigationBarExt3.CausesValidation = false;
            this.navigationBarExt3.ItemDisableTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.navigationBarExt3.ItemEnterBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(153)))), ((int)(((byte)(204)))), ((int)(((byte)(153)))));
            this.navigationBarExt3.ItemInterval = 4;
            this.navigationBarExt3.ItemNormalBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(204)))), ((int)(((byte)(153)))));
            navigationBarItem26.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem26.BackRectF")));
            navigationBarItem26.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem26.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem26.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem26.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem26.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem26.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath26.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem26.Path = graphicsPath26;
            navigationBarItem26.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem26.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem26.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem26.SymbolRectF")));
            navigationBarItem26.Text = "一级菜单";
            navigationBarItem26.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem27.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem27.BackRectF")));
            navigationBarItem27.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem27.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem27.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem27.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem27.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem27.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath27.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem27.Path = graphicsPath27;
            navigationBarItem27.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem27.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem27.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem27.SymbolRectF")));
            navigationBarItem27.Text = "二级菜单";
            navigationBarItem27.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem28.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem28.BackRectF")));
            navigationBarItem28.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem28.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem28.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem28.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem28.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem28.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath28.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem28.Path = graphicsPath28;
            navigationBarItem28.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem28.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem28.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem28.SymbolRectF")));
            navigationBarItem28.Text = "三级菜单";
            navigationBarItem28.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem29.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem29.BackRectF")));
            navigationBarItem29.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem29.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem29.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem29.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem29.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem29.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath29.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem29.Path = graphicsPath29;
            navigationBarItem29.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem29.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem29.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem29.SymbolRectF")));
            navigationBarItem29.Text = "四级菜单";
            navigationBarItem29.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem30.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem30.BackRectF")));
            navigationBarItem30.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem30.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem30.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem30.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem30.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem30.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath30.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem30.Path = graphicsPath30;
            navigationBarItem30.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem30.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem30.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem30.SymbolRectF")));
            navigationBarItem30.Text = "五级菜单";
            navigationBarItem30.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            this.navigationBarExt3.Items.Add(navigationBarItem26);
            this.navigationBarExt3.Items.Add(navigationBarItem27);
            this.navigationBarExt3.Items.Add(navigationBarItem28);
            this.navigationBarExt3.Items.Add(navigationBarItem29);
            this.navigationBarExt3.Items.Add(navigationBarItem30);
            this.navigationBarExt3.ItemStyle = WinformControlLibraryExtension.NavigationBarExt.ItemStyles.Parallelogram;
            this.navigationBarExt3.Location = new System.Drawing.Point(367, 118);
            this.navigationBarExt3.Name = "navigationBarExt3";
            this.navigationBarExt3.Size = new System.Drawing.Size(570, 24);
            this.navigationBarExt3.SymbolColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.navigationBarExt3.TabIndex = 4;
            this.navigationBarExt3.Text = "navigationBarExt3";
            // 
            // navigationBarExt2
            // 
            this.navigationBarExt2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.navigationBarExt2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(183)))), ((int)(((byte)(107)))));
            this.navigationBarExt2.CausesValidation = false;
            this.navigationBarExt2.ItemDisableTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.navigationBarExt2.ItemInterval = 4;
            navigationBarItem31.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem31.BackRectF")));
            navigationBarItem31.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem31.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem31.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem31.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem31.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem31.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath31.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem31.Path = graphicsPath31;
            navigationBarItem31.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem31.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem31.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem31.SymbolRectF")));
            navigationBarItem31.Text = "一级菜单";
            navigationBarItem31.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem32.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem32.BackRectF")));
            navigationBarItem32.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem32.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem32.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem32.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem32.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem32.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath32.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem32.Path = graphicsPath32;
            navigationBarItem32.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem32.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem32.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem32.SymbolRectF")));
            navigationBarItem32.Text = "二级菜单";
            navigationBarItem32.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem33.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem33.BackRectF")));
            navigationBarItem33.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem33.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem33.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem33.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem33.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem33.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath33.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem33.Path = graphicsPath33;
            navigationBarItem33.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem33.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem33.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem33.SymbolRectF")));
            navigationBarItem33.Text = "三级菜单";
            navigationBarItem33.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem34.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem34.BackRectF")));
            navigationBarItem34.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem34.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem34.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem34.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem34.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem34.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath34.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem34.Path = graphicsPath34;
            navigationBarItem34.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem34.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem34.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem34.SymbolRectF")));
            navigationBarItem34.Text = "四级菜单";
            navigationBarItem34.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem35.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem35.BackRectF")));
            navigationBarItem35.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem35.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem35.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem35.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem35.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem35.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath35.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem35.Path = graphicsPath35;
            navigationBarItem35.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem35.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem35.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem35.SymbolRectF")));
            navigationBarItem35.Text = "五级菜单";
            navigationBarItem35.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            this.navigationBarExt2.Items.Add(navigationBarItem31);
            this.navigationBarExt2.Items.Add(navigationBarItem32);
            this.navigationBarExt2.Items.Add(navigationBarItem33);
            this.navigationBarExt2.Items.Add(navigationBarItem34);
            this.navigationBarExt2.Items.Add(navigationBarItem35);
            this.navigationBarExt2.Location = new System.Drawing.Point(367, 87);
            this.navigationBarExt2.Name = "navigationBarExt2";
            this.navigationBarExt2.Size = new System.Drawing.Size(570, 24);
            this.navigationBarExt2.SymbolColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.navigationBarExt2.TabIndex = 3;
            this.navigationBarExt2.Text = "navigationBarExt1";
            this.navigationBarExt2.ItemClick += new WinformControlLibraryExtension.NavigationBarExt.ItemClickEventHandler(this.navigationBarExt2_NavigationItemClick);
            // 
            // navigationBarExt1
            // 
            this.navigationBarExt1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.navigationBarExt1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(183)))), ((int)(((byte)(107)))));
            this.navigationBarExt1.CausesValidation = false;
            this.navigationBarExt1.ItemDisableTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.navigationBarExt1.ItemInterval = 4;
            this.navigationBarExt1.ItemNormalBackColor = System.Drawing.Color.Empty;
            this.navigationBarExt1.ItemNormalTextColor = System.Drawing.Color.Gray;
            navigationBarItem36.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem36.BackRectF")));
            navigationBarItem36.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem36.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem36.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem36.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem36.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem36.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath36.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem36.Path = graphicsPath36;
            navigationBarItem36.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem36.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem36.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem36.SymbolRectF")));
            navigationBarItem36.Text = "一级菜单";
            navigationBarItem36.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem37.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem37.BackRectF")));
            navigationBarItem37.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem37.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem37.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem37.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem37.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem37.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath37.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem37.Path = graphicsPath37;
            navigationBarItem37.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem37.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem37.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem37.SymbolRectF")));
            navigationBarItem37.Text = "二级菜单";
            navigationBarItem37.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem38.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem38.BackRectF")));
            navigationBarItem38.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem38.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem38.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem38.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem38.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem38.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath38.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem38.Path = graphicsPath38;
            navigationBarItem38.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem38.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem38.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem38.SymbolRectF")));
            navigationBarItem38.Text = "三级菜单";
            navigationBarItem38.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem39.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem39.BackRectF")));
            navigationBarItem39.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem39.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem39.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem39.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem39.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem39.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath39.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem39.Path = graphicsPath39;
            navigationBarItem39.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem39.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem39.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem39.SymbolRectF")));
            navigationBarItem39.Text = "四级菜单";
            navigationBarItem39.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            navigationBarItem40.BackRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem40.BackRectF")));
            navigationBarItem40.DisableBackColor = System.Drawing.Color.Empty;
            navigationBarItem40.DisableTextColor = System.Drawing.Color.Empty;
            navigationBarItem40.EnterBackColor = System.Drawing.Color.Empty;
            navigationBarItem40.EnterTextColor = System.Drawing.Color.Empty;
            navigationBarItem40.NormalBackColor = System.Drawing.Color.Empty;
            navigationBarItem40.NormalTextColor = System.Drawing.Color.Empty;
            graphicsPath40.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            navigationBarItem40.Path = graphicsPath40;
            navigationBarItem40.SelectedBackColor = System.Drawing.Color.Empty;
            navigationBarItem40.SelectedTextColor = System.Drawing.Color.Empty;
            navigationBarItem40.SymbolRectF = ((System.Drawing.RectangleF)(resources.GetObject("navigationBarItem40.SymbolRectF")));
            navigationBarItem40.Text = "五级菜单";
            navigationBarItem40.TextSize = new System.Drawing.SizeF(66.29817F, 18.5625F);
            this.navigationBarExt1.Items.Add(navigationBarItem36);
            this.navigationBarExt1.Items.Add(navigationBarItem37);
            this.navigationBarExt1.Items.Add(navigationBarItem38);
            this.navigationBarExt1.Items.Add(navigationBarItem39);
            this.navigationBarExt1.Items.Add(navigationBarItem40);
            this.navigationBarExt1.ItemStyle = WinformControlLibraryExtension.NavigationBarExt.ItemStyles.Symbol;
            this.navigationBarExt1.Location = new System.Drawing.Point(367, 25);
            this.navigationBarExt1.Name = "navigationBarExt1";
            this.navigationBarExt1.Size = new System.Drawing.Size(570, 24);
            this.navigationBarExt1.SymbolColor = System.Drawing.Color.Gray;
            this.navigationBarExt1.TabIndex = 1;
            this.navigationBarExt1.Text = "navigationBarExt2";
            // 
            // propertyGrid1
            // 
            this.propertyGrid1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.propertyGrid1.Location = new System.Drawing.Point(0, 0);
            this.propertyGrid1.Name = "propertyGrid1";
            this.propertyGrid1.SelectedObject = this.navigationBarExt1;
            this.propertyGrid1.Size = new System.Drawing.Size(350, 537);
            this.propertyGrid1.TabIndex = 17;
            // 
            // NavigationBarExtForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(247)))), ((int)(((byte)(240)))));
            this.ClientSize = new System.Drawing.Size(959, 536);
            this.Controls.Add(this.propertyGrid1);
            this.Controls.Add(this.navigationBarExt8);
            this.Controls.Add(this.navigationBarExt7);
            this.Controls.Add(this.navigationBarExt6);
            this.Controls.Add(this.navigationBarExt5);
            this.Controls.Add(this.navigationBarExt4);
            this.Controls.Add(this.navigationBarExt3);
            this.Controls.Add(this.navigationBarExt2);
            this.Controls.Add(this.navigationBarExt1);
            this.Name = "NavigationBarExtForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "面包屑导航栏控件";
            this.ResumeLayout(false);

        }

        #endregion

        private WinformControlLibraryExtension.NavigationBarExt navigationBarExt2;
        private WinformControlLibraryExtension.NavigationBarExt navigationBarExt3;
        private WinformControlLibraryExtension.NavigationBarExt navigationBarExt4;
        private WinformControlLibraryExtension.NavigationBarExt navigationBarExt5;
        private WinformControlLibraryExtension.NavigationBarExt navigationBarExt1;
        private WinformControlLibraryExtension.NavigationBarExt navigationBarExt6;
        private WinformControlLibraryExtension.NavigationBarExt navigationBarExt7;
        private WinformControlLibraryExtension.NavigationBarExt navigationBarExt8;
        private System.Windows.Forms.PropertyGrid propertyGrid1;
    }
}